# Generated by Django 4.1.3 on 2025-05-29 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digitizingestimate',
            name='Kind_Stitches',
        ),
        migrations.RemoveField(
            model_name='digitizingestimate',
            name='artwork',
        ),
        migrations.RemoveField(
            model_name='digitizingestimate',
            name='auto_thread_cutting',
        ),
        migrations.RemoveField(
            model_name='digitizingestimate',
            name='name_of_colors',
        ),
        migrations.RemoveField(
            model_name='digitizingestimate',
            name='pricing_model_type',
        ),
        migrations.RemoveField(
            model_name='digitizingestimate',
            name='stitched_image',
        ),
        migrations.RemoveField(
            model_name='digitizingestimate',
            name='tackle_or_applique',
        ),
        migrations.RemoveField(
            model_name='digitizingestimate',
            name='time_frame',
        ),
        migrations.RemoveField(
            model_name='digitizingorder',
            name='Kind_Stitches',
        ),
        migrations.RemoveField(
            model_name='digitizingorder',
            name='artwork',
        ),
        migrations.RemoveField(
            model_name='digitizingorder',
            name='auto_thread_cutting',
        ),
        migrations.RemoveField(
            model_name='digitizingorder',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='digitizingorder',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='digitizingorder',
            name='name_of_colors',
        ),
        migrations.RemoveField(
            model_name='digitizingorder',
            name='preview_image',
        ),
        migrations.RemoveField(
            model_name='digitizingorder',
            name='preview_pdf',
        ),
        migrations.RemoveField(
            model_name='digitizingorder',
            name='pricing_model_type',
        ),
        migrations.RemoveField(
            model_name='digitizingorder',
            name='stitched_image',
        ),
        migrations.RemoveField(
            model_name='digitizingorder',
            name='tackle_or_applique',
        ),
        migrations.RemoveField(
            model_name='digitizingorder',
            name='time_frame',
        ),
        migrations.RemoveField(
            model_name='digitizingorder',
            name='total',
        ),
        migrations.AddField(
            model_name='digitizingestimate',
            name='file',
            field=models.FileField(blank=True, default='', max_length=1000, null=True, upload_to='app/files'),
        ),
        migrations.AddField(
            model_name='digitizingestimate',
            name='height_for_admin',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Height'),
        ),
        migrations.AddField(
            model_name='digitizingestimate',
            name='payment_status',
            field=models.CharField(choices=[('Pending Payment', 'Pending Payment'), ('Success Payment', 'Success Payment')], default='', max_length=250),
        ),
        migrations.AddField(
            model_name='digitizingestimate',
            name='po_no',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='digitizingestimate',
            name='required_blending',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Not Sure', 'Not Sure')], default='', max_length=255, verbose_name='Do You Required Blending'),
        ),
        migrations.AddField(
            model_name='digitizingestimate',
            name='width_for_admin',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Width'),
        ),
        migrations.AddField(
            model_name='digitizingorder',
            name='file',
            field=models.FileField(blank=True, default='', max_length=1000, null=True, upload_to='app/files'),
        ),
        migrations.AddField(
            model_name='digitizingorder',
            name='height_for_admin',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Height'),
        ),
        migrations.AddField(
            model_name='digitizingorder',
            name='is_free',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='digitizingorder',
            name='po_no',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='digitizingorder',
            name='required_blending',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Not Sure', 'Not Sure')], default='', max_length=255, verbose_name='Do You Required Blending'),
        ),
        migrations.AddField(
            model_name='digitizingorder',
            name='width_for_admin',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Width'),
        ),
        migrations.AlterField(
            model_name='digitizingestimate',
            name='Sew_Out_Sample',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=255, verbose_name='Real Sew out'),
        ),
        migrations.AlterField(
            model_name='digitizingestimate',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Total Price'),
        ),
        migrations.AlterField(
            model_name='digitizingestimate',
            name='design_format',
            field=models.CharField(max_length=255, verbose_name='Required Format'),
        ),
        migrations.AlterField(
            model_name='digitizingestimate',
            name='instructions_for_user',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Designer Comment'),
        ),
        migrations.AlterField(
            model_name='digitizingestimate',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Process', 'In Process'), ('Completed', 'Completed')], default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='digitizingestimate',
            name='type',
            field=models.CharField(max_length=255, verbose_name='Fabric'),
        ),
        migrations.AlterField(
            model_name='digitizingorder',
            name='Sew_Out_Sample',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=255, verbose_name='Real Sew out'),
        ),
        migrations.AlterField(
            model_name='digitizingorder',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Total Price'),
        ),
        migrations.AlterField(
            model_name='digitizingorder',
            name='design_format',
            field=models.CharField(max_length=255, verbose_name='Required Format'),
        ),
        migrations.AlterField(
            model_name='digitizingorder',
            name='instructions_for_user',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Designer Comment'),
        ),
        migrations.AlterField(
            model_name='digitizingorder',
            name='type',
            field=models.CharField(max_length=255, verbose_name='Fabric'),
        ),
        migrations.CreateModel(
            name='VectorOrderArtwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=1000, upload_to='app/artwork')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='app.vectororder')),
            ],
        ),
        migrations.CreateModel(
            name='VectorEstimateArtwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=1000, upload_to='app/artwork')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='app.vectorestimate')),
            ],
        ),
        migrations.CreateModel(
            name='PatchOrderArtwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=1000, upload_to='app/artwork')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='app.patchesorder')),
            ],
        ),
        migrations.CreateModel(
            name='PatchEstimateArtwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=1000, upload_to='app/artwork')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='app.patchesestimates')),
            ],
        ),
        migrations.CreateModel(
            name='DigitizingOrderArtwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=1000, upload_to='app/artwork')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='app.digitizingorder')),
            ],
        ),
        migrations.CreateModel(
            name='DigitizingEstimateArtwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=1000, upload_to='app/artwork')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='app.digitizingestimate')),
            ],
        ),
    ]
