# Generated by Django 4.1.3 on 2025-05-29 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_digitizingestimate_kind_stitches_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patchesestimates',
            old_name='contact_no',
            new_name='number_of_patches',
        ),
        migrations.RenameField(
            model_name='patchesestimates',
            old_name='stitched_image',
            new_name='thumbnail_image',
        ),
        migrations.RenameField(
            model_name='patchesorder',
            old_name='contact_no',
            new_name='number_of_patches',
        ),
        migrations.RenameField(
            model_name='patchesorder',
            old_name='preview_image',
            new_name='thumbnail_image',
        ),
        migrations.RenameField(
            model_name='vectorestimate',
            old_name='height',
            new_name='po_no',
        ),
        migrations.RenameField(
            model_name='vectorestimate',
            old_name='stitched_image',
            new_name='thumbnail_image',
        ),
        migrations.RenameField(
            model_name='vectororder',
            old_name='height',
            new_name='po_no',
        ),
        migrations.RenameField(
            model_name='vectororder',
            old_name='preview_image',
            new_name='thumbnail_image',
        ),
        migrations.RemoveField(
            model_name='digitizingestimate',
            name='file',
        ),
        migrations.RemoveField(
            model_name='digitizingorder',
            name='file',
        ),
        migrations.RemoveField(
            model_name='patchesestimates',
            name='artwork',
        ),
        migrations.RemoveField(
            model_name='patchesestimates',
            name='backing_material',
        ),
        migrations.RemoveField(
            model_name='patchesestimates',
            name='base_material',
        ),
        migrations.RemoveField(
            model_name='patchesestimates',
            name='border_edge',
        ),
        migrations.RemoveField(
            model_name='patchesestimates',
            name='embroidery',
        ),
        migrations.RemoveField(
            model_name='patchesestimates',
            name='name_of_colors',
        ),
        migrations.RemoveField(
            model_name='patchesestimates',
            name='order_size',
        ),
        migrations.RemoveField(
            model_name='patchesestimates',
            name='pricing_model_type',
        ),
        migrations.RemoveField(
            model_name='patchesestimates',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='patchesestimates',
            name='time_frame',
        ),
        migrations.RemoveField(
            model_name='patchesorder',
            name='artwork',
        ),
        migrations.RemoveField(
            model_name='patchesorder',
            name='backing_material',
        ),
        migrations.RemoveField(
            model_name='patchesorder',
            name='base_material',
        ),
        migrations.RemoveField(
            model_name='patchesorder',
            name='border_edge',
        ),
        migrations.RemoveField(
            model_name='patchesorder',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='patchesorder',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='patchesorder',
            name='embroidery',
        ),
        migrations.RemoveField(
            model_name='patchesorder',
            name='name_of_colors',
        ),
        migrations.RemoveField(
            model_name='patchesorder',
            name='order_size',
        ),
        migrations.RemoveField(
            model_name='patchesorder',
            name='preview_pdf',
        ),
        migrations.RemoveField(
            model_name='patchesorder',
            name='pricing_model_type',
        ),
        migrations.RemoveField(
            model_name='patchesorder',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='patchesorder',
            name='stitched_image',
        ),
        migrations.RemoveField(
            model_name='patchesorder',
            name='time_frame',
        ),
        migrations.RemoveField(
            model_name='patchesorder',
            name='total',
        ),
        migrations.RemoveField(
            model_name='vectorestimate',
            name='Color_Scheme',
        ),
        migrations.RemoveField(
            model_name='vectorestimate',
            name='artwork',
        ),
        migrations.RemoveField(
            model_name='vectorestimate',
            name='name_of_colors',
        ),
        migrations.RemoveField(
            model_name='vectorestimate',
            name='pricing_model_type',
        ),
        migrations.RemoveField(
            model_name='vectorestimate',
            name='time_frame',
        ),
        migrations.RemoveField(
            model_name='vectorestimate',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='vectorestimate',
            name='use_for',
        ),
        migrations.RemoveField(
            model_name='vectorestimate',
            name='width',
        ),
        migrations.RemoveField(
            model_name='vectororder',
            name='Color_Scheme',
        ),
        migrations.RemoveField(
            model_name='vectororder',
            name='artwork',
        ),
        migrations.RemoveField(
            model_name='vectororder',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='vectororder',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='vectororder',
            name='name_of_colors',
        ),
        migrations.RemoveField(
            model_name='vectororder',
            name='preview_pdf',
        ),
        migrations.RemoveField(
            model_name='vectororder',
            name='pricing_model_type',
        ),
        migrations.RemoveField(
            model_name='vectororder',
            name='stitched_image',
        ),
        migrations.RemoveField(
            model_name='vectororder',
            name='time_frame',
        ),
        migrations.RemoveField(
            model_name='vectororder',
            name='total',
        ),
        migrations.RemoveField(
            model_name='vectororder',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='vectororder',
            name='use_for',
        ),
        migrations.RemoveField(
            model_name='vectororder',
            name='width',
        ),
        migrations.AddField(
            model_name='digitizingestimate',
            name='thumbnail_image',
            field=models.ImageField(blank=True, default='', max_length=1000, null=True, upload_to='app/images'),
        ),
        migrations.AddField(
            model_name='digitizingorder',
            name='thumbnail_image',
            field=models.ImageField(blank=True, default='', max_length=1000, null=True, upload_to='app/images'),
        ),
        migrations.AddField(
            model_name='patchesestimates',
            name='border',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='patchesestimates',
            name='height_for_admin',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Height'),
        ),
        migrations.AddField(
            model_name='patchesestimates',
            name='patch_backing',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='patchesestimates',
            name='patch_type',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='patchesestimates',
            name='payment_status',
            field=models.CharField(choices=[('Pending Payment', 'Pending Payment'), ('Success Payment', 'Success Payment')], default='', max_length=250),
        ),
        migrations.AddField(
            model_name='patchesestimates',
            name='unit',
            field=models.CharField(choices=[('inches', 'inches'), ('mm', 'mm'), ('cm', 'cm')], default='', max_length=255),
        ),
        migrations.AddField(
            model_name='patchesestimates',
            name='width_for_admin',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Width'),
        ),
        migrations.AddField(
            model_name='patchesorder',
            name='border',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='patchesorder',
            name='height_for_admin',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Height'),
        ),
        migrations.AddField(
            model_name='patchesorder',
            name='is_free',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='patchesorder',
            name='patch_backing',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='patchesorder',
            name='patch_type',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='patchesorder',
            name='unit',
            field=models.CharField(choices=[('inches', 'inches'), ('mm', 'mm'), ('cm', 'cm')], default='', max_length=255),
        ),
        migrations.AddField(
            model_name='patchesorder',
            name='width_for_admin',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Width'),
        ),
        migrations.AddField(
            model_name='vectorestimate',
            name='payment_status',
            field=models.CharField(choices=[('Pending Payment', 'Pending Payment'), ('Success Payment', 'Success Payment')], default='', max_length=250),
        ),
        migrations.AddField(
            model_name='vectororder',
            name='is_free',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='patchesestimates',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Total Price'),
        ),
        migrations.AlterField(
            model_name='patchesestimates',
            name='delivery_address',
            field=models.CharField(max_length=255, verbose_name='Shipping Address'),
        ),
        migrations.AlterField(
            model_name='patchesestimates',
            name='instructions_for_user',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Designer Comment'),
        ),
        migrations.AlterField(
            model_name='patchesestimates',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Process', 'In Process'), ('Completed', 'Completed')], default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='patchesorder',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Total Price'),
        ),
        migrations.AlterField(
            model_name='patchesorder',
            name='delivery_address',
            field=models.CharField(max_length=255, verbose_name='Shipping Address'),
        ),
        migrations.AlterField(
            model_name='patchesorder',
            name='instructions_for_user',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Designer Comment'),
        ),
        migrations.AlterField(
            model_name='vectorestimate',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Total Price'),
        ),
        migrations.AlterField(
            model_name='vectorestimate',
            name='instructions_for_user',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Designer Comment'),
        ),
        migrations.AlterField(
            model_name='vectorestimate',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Process', 'In Process'), ('Completed', 'Completed')], default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='vectororder',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Total Price'),
        ),
        migrations.AlterField(
            model_name='vectororder',
            name='instructions_for_user',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Designer Comment'),
        ),
        migrations.CreateModel(
            name='VectorOrderFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=1000, upload_to='app/files')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='app.vectororder')),
            ],
        ),
        migrations.CreateModel(
            name='VectorEstimateFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=1000, upload_to='app/files')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='app.vectorestimate')),
            ],
        ),
        migrations.CreateModel(
            name='PatchOrderFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=1000, upload_to='app/files')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='app.patchesorder')),
            ],
        ),
        migrations.CreateModel(
            name='PatchEstimateFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=1000, upload_to='app/files')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='app.patchesestimates')),
            ],
        ),
        migrations.CreateModel(
            name='DigitizingOrderFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=1000, upload_to='app/artwork')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='app.digitizingorder')),
            ],
        ),
        migrations.CreateModel(
            name='DigitizingEstimateFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=1000, upload_to='app/files')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='app.digitizingestimate')),
            ],
        ),
    ]
