# Generated by Django 4.1.3 on 2025-05-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_contact_no_patchesestimates_number_of_patches_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vectorestimate',
            name='height',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vectorestimate',
            name='unit',
            field=models.CharField(choices=[('inches', 'inches'), ('mm', 'mm'), ('cm', 'cm')], default='', max_length=255),
        ),
        migrations.AddField(
            model_name='vectorestimate',
            name='width',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vectororder',
            name='height',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vectororder',
            name='unit',
            field=models.CharField(choices=[('inches', 'inches'), ('mm', 'mm'), ('cm', 'cm')], default='', max_length=255),
        ),
        migrations.AddField(
            model_name='vectororder',
            name='width',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
