# Generated by Django 4.1.3 on 2025-05-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_vectorestimate_height_vectorestimate_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patchesorder',
            name='color_separation',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=255, verbose_name='Do You Required Color Separation?'),
        ),
        migrations.AddField(
            model_name='vectororder',
            name='color_separation',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=255, verbose_name='Do You Required Color Separation?'),
        ),
    ]
