# Generated by Django 4.1.3 on 2025-05-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_patchesorder_color_separation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patchesestimates',
            name='po_no',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patchesorder',
            name='po_no',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
