# Generated by Django 4.1.3 on 2025-06-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_patchesestimates_po_no_patchesorder_po_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patchesorder',
            name='color_separation',
        ),
        migrations.AddField(
            model_name='vectorestimate',
            name='color_separation',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=255, verbose_name='Do You Required Color Separation?'),
        ),
    ]
