# Generated by Django 4.1.3 on 2025-06-02 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_patchesorder_color_separation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='coupon_discount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='discount_title',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='grand_total',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='other_amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='other_amount_title',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='shipping',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='shipping_title',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='subtotal',
        ),
    ]
