# Generated by Django 4.1.3 on 2025-06-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_date_invoice_invoice_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='item_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='po_no',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
