# Generated by Django 4.1.3 on 2025-06-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_invoiceitem_item_id_invoiceitem_po_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitizingorder',
            name='edit_remarks',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='patchesorder',
            name='edit_remarks',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='vectororder',
            name='edit_remarks',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='digitizingestimate',
            name='order_status',
            field=models.CharField(choices=[('On Progress', 'On Progress'), ('Delivered', 'Delivered'), ('Edited', 'Edited')], default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='digitizingorder',
            name='order_status',
            field=models.CharField(choices=[('On Progress', 'On Progress'), ('Delivered', 'Delivered'), ('Edited', 'Edited')], default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='edits',
            name='order_status',
            field=models.CharField(choices=[('On Progress', 'On Progress'), ('Delivered', 'Delivered'), ('Edited', 'Edited')], default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='patchesestimates',
            name='order_status',
            field=models.CharField(choices=[('On Progress', 'On Progress'), ('Delivered', 'Delivered'), ('Edited', 'Edited')], default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='patchesorder',
            name='order_status',
            field=models.CharField(choices=[('On Progress', 'On Progress'), ('Delivered', 'Delivered'), ('Edited', 'Edited')], default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='vectorestimate',
            name='order_status',
            field=models.CharField(choices=[('On Progress', 'On Progress'), ('Delivered', 'Delivered'), ('Edited', 'Edited')], default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='vectororder',
            name='order_status',
            field=models.CharField(choices=[('On Progress', 'On Progress'), ('Delivered', 'Delivered'), ('Edited', 'Edited')], default='', max_length=250),
        ),
    ]
