# Generated by Django 4.1.3 on 2025-06-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_digitizingorder_edit_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitizingestimate',
            name='edit_remarks',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='patchesestimates',
            name='edit_remarks',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='vectorestimate',
            name='edit_remarks',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
