# Generated by Django 4.1.3 on 2025-06-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_digitizingestimate_edit_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
