# Generated by Django 4.1.3 on 2025-06-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_invoiceitem_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='po_no',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
