# Generated by Django 4.1.3 on 2025-06-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_invoiceitem_po_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitizingestimatefile',
            name='file_status',
            field=models.CharField(choices=[('original', 'Original Upload'), ('after_edit', 'Uploaded After Edit')], default='', max_length=250),
        ),
        migrations.AddField(
            model_name='digitizingestimatefile',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='digitizingorderfile',
            name='file_status',
            field=models.CharField(choices=[('original', 'Original Upload'), ('after_edit', 'Uploaded After Edit')], default='', max_length=250),
        ),
        migrations.AddField(
            model_name='digitizingorderfile',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='patchestimatefile',
            name='file_status',
            field=models.CharField(choices=[('original', 'Original Upload'), ('after_edit', 'Uploaded After Edit')], default='', max_length=250),
        ),
        migrations.AddField(
            model_name='patchestimatefile',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='patchorderfile',
            name='file_status',
            field=models.CharField(choices=[('original', 'Original Upload'), ('after_edit', 'Uploaded After Edit')], default='', max_length=250),
        ),
        migrations.AddField(
            model_name='patchorderfile',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vectorestimatefile',
            name='file_status',
            field=models.CharField(choices=[('original', 'Original Upload'), ('after_edit', 'Uploaded After Edit')], default='', max_length=250),
        ),
        migrations.AddField(
            model_name='vectorestimatefile',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vectororderfile',
            name='file_status',
            field=models.CharField(choices=[('original', 'Original Upload'), ('after_edit', 'Uploaded After Edit')], default='', max_length=250),
        ),
        migrations.AddField(
            model_name='vectororderfile',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'PAID'), ('UNPAID', 'UNPAID')], default='UNPAID', max_length=20),
        ),
    ]
