# Generated by Django 4.1.3 on 2025-06-04 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0015_digitizingestimatefile_file_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patchesestimates',
            old_name='number_of_stitches',
            new_name='number_of_colors_for_admin',
        ),
        migrations.RenameField(
            model_name='patchesorder',
            old_name='number_of_stitches',
            new_name='number_of_colors_for_admin',
        ),
        migrations.AddField(
            model_name='patchesestimates',
            name='shipping_address',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Shipping Address'),
        ),
        migrations.AddField(
            model_name='patchesorder',
            name='shipping_address',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Shipping Address'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patchesestimates',
            name='instructions_for_user',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Designer Instructions'),
        ),
        migrations.AlterField(
            model_name='patchesorder',
            name='instructions_for_user',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Designer Instructions'),
        ),
    ]
