# Generated by Django 4.1.3 on 2025-06-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_number_of_stitches_patchesestimates_number_of_colors_for_admin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='digitizingestimate',
            options={'verbose_name_plural': '04 Digitizing Quotes'},
        ),
        migrations.AlterModelOptions(
            name='digitizingorder',
            options={'verbose_name_plural': '01 Digitizing Orders'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name_plural': '07 Invoice'},
        ),
        migrations.AlterModelOptions(
            name='patchesestimates',
            options={'verbose_name_plural': '06 Patches Quotes'},
        ),
        migrations.AlterModelOptions(
            name='patchesorder',
            options={'verbose_name_plural': '03 Patches Orders'},
        ),
        migrations.AlterModelOptions(
            name='vectorestimate',
            options={'verbose_name_plural': '05 Vector Quotes'},
        ),
        migrations.AlterModelOptions(
            name='vectororder',
            options={'verbose_name_plural': '02 Vector Orders'},
        ),
        migrations.AddField(
            model_name='profile',
            name='invoice_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='profile',
            name='reference',
            field=models.CharField(blank=True, choices=[('search_engine', 'Search Engine'), ('customer_reference', 'Customer Reference'), ('salesman', 'Salesman'), ('other', 'Other')], max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='patchesestimates',
            name='number_of_colors_for_admin',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Number Of Colors'),
        ),
        migrations.AlterField(
            model_name='patchesorder',
            name='number_of_colors_for_admin',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Number Of Colors'),
        ),
    ]
