# Generated by Django 4.1.3 on 2025-06-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_digitizingestimate_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BackingMaterial',
        ),
        migrations.DeleteModel(
            name='BaseMaterial',
        ),
        migrations.DeleteModel(
            name='BorderEdge',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.RemoveField(
            model_name='couponusage',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='edits',
            name='design_digitizing',
        ),
        migrations.RemoveField(
            model_name='edits',
            name='design_patches',
        ),
        migrations.RemoveField(
            model_name='edits',
            name='design_vector',
        ),
        migrations.RemoveField(
            model_name='edits',
            name='user',
        ),
        migrations.DeleteModel(
            name='Embroidery',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='openticket',
            name='design_digitizing',
        ),
        migrations.RemoveField(
            model_name='openticket',
            name='design_patches',
        ),
        migrations.RemoveField(
            model_name='openticket',
            name='design_vector',
        ),
        migrations.RemoveField(
            model_name='openticket',
            name='user',
        ),
        migrations.DeleteModel(
            name='Package',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='user',
        ),
        migrations.AlterField(
            model_name='digitizingestimate',
            name='order_type',
            field=models.CharField(choices=[('Digitizing', 'Digitizing'), ('Vector Conversion', 'Vector Conversion'), ('Embroidery Patches', 'Embroidery Patches')], default='Digitizing', max_length=255),
        ),
        migrations.AlterField(
            model_name='digitizingorder',
            name='order_type',
            field=models.CharField(choices=[('Digitizing', 'Digitizing'), ('Vector Conversion', 'Vector Conversion'), ('Embroidery Patches', 'Embroidery Patches')], default='Digitizing', max_length=255),
        ),
        migrations.AlterField(
            model_name='patchesestimates',
            name='order_type',
            field=models.CharField(choices=[('Digitizing', 'Digitizing'), ('Vector Conversion', 'Vector Conversion'), ('Embroidery Patches', 'Embroidery Patches')], default='Embroidery Patches', max_length=255),
        ),
        migrations.AlterField(
            model_name='patchesorder',
            name='order_type',
            field=models.CharField(choices=[('Digitizing', 'Digitizing'), ('Vector Conversion', 'Vector Conversion'), ('Embroidery Patches', 'Embroidery Patches')], default='Embroidery Patches', max_length=255),
        ),
        migrations.AlterField(
            model_name='vectorestimate',
            name='order_type',
            field=models.CharField(choices=[('Digitizing', 'Digitizing'), ('Vector Conversion', 'Vector Conversion'), ('Embroidery Patches', 'Embroidery Patches')], default='Vector Conversion', max_length=255),
        ),
        migrations.AlterField(
            model_name='vectororder',
            name='order_type',
            field=models.CharField(choices=[('Digitizing', 'Digitizing'), ('Vector Conversion', 'Vector Conversion'), ('Embroidery Patches', 'Embroidery Patches')], default='Vector Conversion', max_length=255),
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
        migrations.DeleteModel(
            name='CouponUsage',
        ),
        migrations.DeleteModel(
            name='Edits',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='OpenTicket',
        ),
        migrations.DeleteModel(
            name='Pricing',
        ),
    ]
