# Generated by Django 4.1.3 on 2025-07-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_delete_backingmaterial_delete_basematerial_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': '08 Profiles'},
        ),
        migrations.AddField(
            model_name='digitizingestimateartwork',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='digitizingorderartwork',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patchestimateartwork',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patchorderartwork',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vectorestimateartwork',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vectororderartwork',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='digitizingorder',
            name='design_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='business_phone_no',
            field=models.CharField(blank=True, max_length=100, verbose_name='Office No'),
        ),
    ]
