# Generated by Django 4.1.3 on 2025-08-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='preview_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='digitizingestimate',
            name='number_of_colors',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='digitizingorder',
            name='number_of_colors',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patchesestimates',
            name='delivery_address',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Shipping Address'),
        ),
        migrations.AlterField(
            model_name='patchesorder',
            name='delivery_address',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Shipping Address'),
        ),
        migrations.AlterField(
            model_name='vectorestimate',
            name='number_of_colors',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vectororder',
            name='number_of_colors',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
