# Generated by Django 4.1.3 on 2025-08-12 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_invoice_preview_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digitizingestimateartwork',
            name='is_edited',
        ),
        migrations.RemoveField(
            model_name='patchestimateartwork',
            name='is_edited',
        ),
        migrations.RemoveField(
            model_name='vectorestimateartwork',
            name='is_edited',
        ),
        migrations.AddField(
            model_name='digitizingestimateartwork',
            name='order_file_type',
            field=models.CharField(blank=True, choices=[('placing_edit', 'Submitted during placing edit'), ('quote_to_order', 'Submitted during quote-to-order conversion')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='patchestimateartwork',
            name='order_file_type',
            field=models.CharField(blank=True, choices=[('placing_edit', 'Submitted during placing edit'), ('quote_to_order', 'Submitted during quote-to-order conversion')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vectorestimateartwork',
            name='order_file_type',
            field=models.CharField(blank=True, choices=[('placing_edit', 'Submitted during placing edit'), ('quote_to_order', 'Submitted during quote-to-order conversion')], max_length=30, null=True),
        ),
    ]
