# Generated by Django 4.1.3 on 2025-08-12 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_digitizingestimateartwork_is_edited_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digitizingorderartwork',
            name='is_edited',
        ),
        migrations.RemoveField(
            model_name='patchorderartwork',
            name='is_edited',
        ),
        migrations.RemoveField(
            model_name='vectororderartwork',
            name='is_edited',
        ),
        migrations.AddField(
            model_name='digitizingorderartwork',
            name='order_file_type',
            field=models.CharField(blank=True, choices=[('placing_edit', 'Submitted during placing edit'), ('quote_to_order', 'Submitted during quote-to-order conversion')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='patchorderartwork',
            name='order_file_type',
            field=models.CharField(blank=True, choices=[('placing_edit', 'Submitted during placing edit'), ('quote_to_order', 'Submitted during quote-to-order conversion')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vectororderartwork',
            name='order_file_type',
            field=models.CharField(blank=True, choices=[('placing_edit', 'Submitted during placing edit'), ('quote_to_order', 'Submitted during quote-to-order conversion')], max_length=30, null=True),
        ),
    ]
