# Generated by Django 4.1.3 on 2025-08-13 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_digitizingorderartwork_is_edited_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitizingorder',
            name='addtitoanl_instructions_quote_to_order',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Additional Instructions When Converting Quote to Order'),
        ),
        migrations.AddField(
            model_name='patchesorder',
            name='addtitoanl_instructions_quote_to_order',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Additional Instructions When Converting Quote to Order'),
        ),
        migrations.AddField(
            model_name='vectororder',
            name='addtitoanl_instructions_quote_to_order',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Additional Instructions When Converting Quote to Order'),
        ),
    ]
